### PR TITLE
edit news from cms

### LINKED ISSUE #80: Allow news home page edits from Netlify CMS
News texts are hardcoded. Update so users can update the text with Netlify's CMS.

If there are more than three, then take the last three entries and add those to the home page.

### LINKED ISSUE #103: "Read More" button on main page is not clickable (desktop and mobile)
I cannot press the "Read More" button on either the desktop or mobile versions of the site.

screen shot 2018-02-15 at 11 32 19 am

### PR DESCRIPTION
**Pull request by Goolzzi**
closes #80 
closes #103

### CODE REVIEW

**Comment by jgwerner** [comment]
@Goolzzi on mouse over, the mouse icon does not change from the pointer to the clicker icon. This does happen in other clickable elements but not with the `Read More` button in the news section.

**Comment by Goolzzi** [comment]
@jgwerner I recognized news was entirely same with blog.
Should I create `news` collection?

**Comment by jgwerner** [comment]
@Goolzzi Right now, it seems that you just add the article (blog entry) and then we list the last three articles in the News section. In other words, even if the blog entry is not a news article, it gets displayed in that section. Correct? If so, we need to either tag blog articles with a News tag and have the system only display items with those tags or create a separate CMS section and only have those in the news section.

**Comment by Goolzzi** [comment]
If contents of article and news are entirely same, 1st option is good but if they are different, 2nd will be good for us?
Which is best for you either adding tag for news or creating new collection for news, do you think? @jgwerner

**Comment by jgwerner** [comment]
@Goolzzi the think is not all blog entries are news items that should be added to the `Press` or `In the News` section. So we just need to segregate normal blogs from news blogs.

**Comment by jgwerner** [comment]
@Goolzzi what is easier? tag or collection?

**Comment by Goolzzi** [comment]
@jgwerner Please check it

**Comment by jgwerner** [comment]
@Goolzzi how do I validate where the tag is located?

**Comment by Goolzzi** [comment]
@jgwerner https://deploy-preview-110--cod-www.netlify.com/admin/#/collections/blog

**Comment by jgwerner** [comment]
@Goolzzi I just added a new article but it does not post on the home page. Should it appear automatically?

**Comment by Goolzzi** [comment]
@jgwerner I think, when we work on the cms admin, it would be reflected in the master branch so the new article couldn't be applied this PR.

**Pull request merged**
